# -*- coding: utf-8 -*-
"""Atividade 3 - Transformadores - IsaacMárvioLimaSantiago.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eeoQFBSqOkUBatG3K2x8SqxEAf0mGWKu

Questão 1
"""

V = 120
a = 8

# figura a
Ra = 8 
Rta = 500 + Ra 

Ia = V/Rta
Pa = (Ia**2)*(Ra)
print(f'a) A potência é igual a {Pa:.4f} W')

# figura b
Rb = Ra * a**2
Rtb = 512 + Rb

Ib = V/Rtb
Pb = (Ib**2)*(Rb)
print(f'b) A potência é igual a P = {Pb:.4f} W')

q = Pb/Pa

print(f'''c) Percebe-se que a potência está sendo melhor aproveitada com o uso do transformador, já que a potência é {q:.4f} vezes maior que na situação sem transformador.''')

"""Questão 2"""

Pa = 10
Za = 8
V = 70.7

Pt = 4*Pa
print(f'a) Pt= {Pt} W ')


I = Pa/V
Z = V/I
print(f'\nb) Z = {Z} ohms')

a = (Z/Za)**0.5
print(f'\nc) Então a relação de espiras é de {a:.0f}:1.')

Va = V/a
print(f'\nd) Va = {Va} V')


print(f'\ne) Para um alto-falante ligado e para 4 as cargas são, respectivamente, {Z:.4f} ohms e {Z/4:.4f} ohms.')

"""Questão 3"""

a = 1/5
Ip = 2
Zc = 2

Ic = a * Ip
Vc = Zc * Ic
print(f'a) Ic = {Ic} A e Vc = {Vc} V.')

Zp = (a**2)*Zc
print(f'\nb) Zp = {Zp:.2f} ohms')

"""Questão 4"""

from math import acos, cos, sin, pi

s = 10000
a = 4800/240
FP = 1 

# Ensaio a curto-circuito
pot1 = 180 #W
v1 = 180 #V
Inom = s/4800

# Ensaio a vazio
pot2 = 60 #W
v2 = 240 #V
I2 = 1.5 # A


Z1 = v1/Inom 
angulo1 = acos(pot1/(v1*Inom))
Z1 = complex(Z1*cos(angulo1), Z1*sin(angulo1))
Req = Z1.real/a**2
Xeq = Z1.imag/a**2

print('a)')
print('Impedância equivalente referenciada ao lado de alta tensão')
print(f'Z1 = {Z1} ohms')
print(f'Rc1 = {Z1.real} ohms')
print(f'X1 = {Z1.imag} ohms')

print('\nImpedância equivalente referenciada ao lado de baixa tensão')
print(f'''Req = {Req} ohms
Xeq = {Xeq} ohms\n''') 



Yex2 = I2/v2 
angulo2 = acos(pot2/(v2*I2))
Yex2 = complex(Yex2*cos(angulo2), -Yex2*sin(angulo2))
Rc2 = 1/Yex2.real 
X2 = 1/-Yex2.imag

print('Impedância de excitação referenciada ao lado de baixa tensão')
print(f'Yex2 = {Yex2} ohms - Admitância')
print(f'''RCb = {Rc2} ohms
XMb = {X2} ohms - para baixa tensão\n''')

print('A impedância de excitação referenciada ao lado de alta tensão')
print(f'''RCa = {Rc2*a**2} ohms
XMa = {X2*a**2} ohms - para alta tensão\n''')


Icarga = s/v2
angcarga1 = acos(FP) 
angcarga = -(acos(FP)*180)/pi 
angcarga2 = ((angcarga+90)*pi)/180 
Icarga1 = complex(Icarga*cos(-angcarga1), Icarga*sin(-angcarga1))
Icarga2 = complex(Icarga*cos(angcarga2), Icarga*sin(angcarga2))
VA = v2 + Req*Icarga1+ Xeq*Icarga2
RT = (abs(VA) - v2)/v2
print(f'b) RT = {RT*100}%')

"""Questão 5 """

from math import acos, cos, sin, pi

a = 12000/240
s = 100000
Inom = s/12000 
FP = 0.8

# Ensaio a curto-circuito
pot1 = 1200 
v1 = 600 

# Ensaio a vazio
pot2 = 60 
v2 = 240 
I2 = 1.5 

Z1 = v1/Inom 
angulo1 = acos(pot1/(v1*Inom))
Z1 = complex(Z1*cos(angulo1), Z1*sin(angulo1))
Req = Z1.real/a**2
Xeq = Z1.imag/a**2

print('a)')
print('Impedância equivalente referenciada ao lado de alta tensão')
print(f'Z1 = {Z1} ohms')
print(f'Rc1 = {Z1.real} ohms')
print(f'X1 = {Z1.imag} ohms')

print('\nImpedância equivalente referenciada ao lado de baixa tensão')
print(f'''Req = {Req} ohms
Xeq = {Xeq} ohms\n''') 

Yex2 = I2/v2 
angulo2 = acos(pot2/(v2*I2))
Yex2 = complex(Yex2*cos(angulo2), -Yex2*sin(angulo2))
Rc2 = 1/Yex2.real 
X2 = 1/-Yex2.imag

print('Impedância de excitação referenciada ao lado de baixa tensão')
print(f'Yex2 = {Yex2} ohms - Admitância')
print(f'''RCb = {Rc2} ohms
XMb = {X2} ohms - para baixa tensão\n''')

print('A impedância de excitação referenciada ao lado de alta tensão')
print(f'''RCa = {Rc2*a**2} ohms
XMa = {X2*a**2} ohms - para alta tensão\n''')

Icarga = s/v2
angcarga1 = acos(FP) 
angcarga = -(acos(FP)*180)/pi 
angcarga2 = ((angcarga+90)*pi)/180 
Icarga1 = complex(Icarga*cos(-angcarga1), Icarga*sin(-angcarga1))
Icarga2 = complex(Icarga*cos(angcarga2), Icarga*sin(angcarga2))
VA = v2 + Req*Icarga1+ Xeq*Icarga2
RT = (abs(VA) - v2)/v2
print(f'a) RT = {RT*100}%')

"""Questão 6"""

# Dados úteis
a = 2400/240
FP = 0.15

# Baixa tensão
Pb = 254 
Vb = 240

S = Pb/FP 
Qb = (S**2 - Pb**2)**0.5

RCb = (Vb**2)/Pb
XMb = (Vb**2)/Qb

# Alta tensão
RCa = RCb * a**2
XMa = complex(0, XMb * a**2)
Zeqa = (RCa * XMa)/(RCa + XMa)
I = 2400/Zeqa
print(f'A corrente pedida é {I} A.')

"""Questão 7 """

from math import acos, cos, sin, pi

a = 24200/220
s = 250000
FP = 0.92

# Ensaio a curto-circuito
pot1 = 1700 #W
v1 = 600 #V
Inom = s/24200 * 0.85

# Ensaio a vazio
pot2 = 1200 #W
I2 = 16 # A
Vnom = 220 * 0.85#V

Z1 = v1/Inom 
angulo1 = acos(pot1/(v1*Inom))
Z1 = complex(Z1*cos(angulo1), Z1*sin(angulo1))
Req = Z1.real/a**2
Xeq = Z1.imag/a**2
print('a)')
print('Impedância equivalente referenciada ao lado de alta tensão')
print(f'Z1 = {Z1} ohms')
print(f'Rc1 = {Z1.real} ohms')
print(f'X1 = {Z1.imag} ohms')

print('\nImpedância equivalente referenciada ao lado de baixa tensão')
print(f'''Req = {Req} ohms
Xeq = {Xeq} ohms\n''') 


Yex2 = I2/Vnom
angulo2 = acos(pot2/(Vnom*I2))
Yex2 = complex(Yex2*cos(angulo2), -Yex2*sin(angulo2))
Rc2 = 1/Yex2.real 
X2 = 1/-Yex2.imag

print('Impedância de excitação referenciada ao lado de baixa tensão')
print(f'Yex2 = {Yex2} ohms - Admitância')
print(f'''RCb = {Rc2} ohms
XMb = {X2} ohms - para baixa tensão\n''')

print('A impedância de excitação referenciada ao lado de alta tensão')
print(f'''RCa = {Rc2*a**2} ohms
XMa = {X2*a**2} ohms - para alta tensão\n''')



Icarga = s/Vnom
angcarga1 = acos(FP) #rad
angcarga = -(acos(FP)*180)/pi #graus
angcarga2 = ((angcarga+90)*pi)/180 #rad
Icarga1 = complex(Icarga*cos(-angcarga1), Icarga*sin(-angcarga1))
Icarga2 = complex(Icarga*cos(angcarga2), Icarga*sin(angcarga2))
VA = Vnom + Req*Icarga1+ Xeq*Icarga2
RT = (abs(VA) - Vnom)/Vnom
print(f'\nb) RT = {RT*100}%')

"""Questão 8 """

from math import acos, cos, sin, pi

a = 8000/277
v2 = 277
s = 100000
Inom2 = s/v2

# Constantes do lado de alta tensão
Rc = 50000
Xm = 10000
Rp = 5 
Xp = 6

# Constantes do lado de baixa tensão
Rs = 0.005 
Xs = 0.006

# Reflexões
Reqp = Rp + Rs*a**2
Xeqp = Xp + Xs*a**2

Reqs = Rs + Rp/a**2
Xeqs = Xs + Xp/a**2
Rcs = Rc/a**2
Xms = Xm/a**2

print(f'''a) Circuito referenciado pelo lado de alta tensão
Reqp = {Reqp}
Xeqp = {Xeqp}
Rc = {Rc}
Xm = {Xm}

Circuito referenciado pelo lado de baixa tensão
Reqs = {Reqs}
Xeqs = {Xeqs}
Rcs = {Rcs}
Xms = {Xms}
      ''')

Znom2 = v2/Inom2
print(f'b) Znom2 = {Znom2} ohms')

FP = 0.85
Is = complex(Inom2*FP, - Inom2 * sin(acos(FP)))

VA = v2 + complex(0.011, 0.0132)*Is

RT = (abs(VA) - v2)/v2
print(f'c) RT = {RT*100}%')

Psaida = s*FP
Pcobre = 0.011*(Inom2**2)
Pnucleo = (abs(VA)**2)/Rc
print(f'''d)
Pcobre = {Pcobre} W
Pnucleo = {Pnucleo} W
Psaida = {Psaida} W''')

n = (Psaida)/(Psaida+Pcobre+Pnucleo)
print(f'e) Eficiência n = {n*100}%')

"""Questão 9 """

from math import sqrt, acos, pi, cos, sin
from numpy import angle
 
Req = 0.20 
Xeq = 0.80
Rc = 300
Xm = 100
a = 0.50

Vs = 282.8/sqrt(2)
angulo1 = (-36.87)*pi/180
IsM = 7.07/sqrt(2)
Is = complex(IsM*cos(angulo1), IsM*sin(angulo1))
V1 = a*Vs
I1 = Is/a
VP = V1 + I1*complex(Req, Xeq)

print(f'''V1 = {V1} V
I1 = {I1} V
VP = {VP} V ''')

Iex = VP/Rc + VP/complex(0, Xm)
Ip = I1 + Iex
VR = (abs(VP) - a*Vs)/(a*Vs)*100
Pent = abs(VP) * abs(Ip) * cos(angle(VP)-angle(Ip))
Psai = abs(Vs) * abs(Is) * cos(angle(Vs)-angle(Is))
n = Psai/Pent * 100

print(f'''Is = {Is} A
Iex = {Iex} A
Ip = {Ip} A
VR = {VR} V
Pentrada = {Pent} W
Psaida = {Psai} W
n = {n}%''')

"""Questão 10 """

from math import acos, cos, sin, pi

a = 230/115
s = 1000


# Ensaio a curto-circuito
pot1 = 38.1
v1 = 17.1 
I1 = 8.7 

# Ensaio a vazio
pot2 = 3.9
v2 = 115 
I2 = 0.11

Z1 = v1/I1 
angulo1 = acos(pot1/(v1*I1))
Z1 = complex(Z1*cos(angulo1), Z1*sin(angulo1))
Req = Z1.real/a**2
Xeq = Z1.imag/a**2

print(f'a)\nZ1 = {Z1} ohms')
print(f'Rc1 = {Z1.real} ohms')
print(f'X1 = {Z1.imag} ohms')
print(f'''Req = {Req} ohms
Xeq = {Xeq} ohms\n''') 

Yex2 = I2/v2
angulo2 = acos(pot2/(v2*I2))
Yex2 = complex(Yex2*cos(angulo2), -Yex2*sin(angulo2))
Rc2 = 1/Yex2.real 
X2 = 1/-Yex2.imag

print(f'Yex2 = {Yex2} ohms')
print(f'''RC = {Rc2} ohms
XM = {X2} ohms\n''') 

Icarga = s/v2
angcarga1 = acos(0.8) 
angcarga = -(acos(0.8)*180)/pi 
angcarga2 = ((angcarga+90)*pi)/180 
Icarga1 = complex(Icarga*cos(-angcarga1), Icarga*sin(-angcarga1))
Icarga2 = complex(Icarga*cos(angcarga2), Icarga*sin(angcarga2))
VA = v2 + Req*Icarga1+ Xeq*Icarga2
RT = (abs(VA) - v2)/v2
print(f'b)\nFP = o.8 atrasado -> RT = {RT*100}%\n')

Icarga = s/v2
angcarga1 = acos(1) 
angcarga = -(acos(1)*180)/pi 
angcarga2 = ((angcarga+90)*pi)/180 
Icarga1 = complex(Icarga*cos(-angcarga1), Icarga*sin(-angcarga1))
Icarga2 = complex(Icarga*cos(angcarga2), Icarga*sin(angcarga2))
VA = v2 + Req*Icarga1+ Xeq*Icarga2
RT = (abs(VA) - v2)/v2
print(f'FP = 1 -> RT = {RT*100}%\n')

Icarga = s/v2
angcarga1 = acos(0.8) 
angcarga = (acos(0.8)*180)/pi 
angcarga2 = ((angcarga+90)*pi)/180 
Icarga1 = complex(Icarga*cos(angcarga1), Icarga*sin(angcarga1))
Icarga2 = complex(Icarga*cos(angcarga2), Icarga*sin(angcarga2))
VA = v2 + Req*Icarga1+ Xeq*Icarga2
RT = (abs(VA) - v2)/v2
print(f'FP = 0.8 Adiantado -> RT = {RT*100}%\n')

"""Questão 11 """

a = 8000/230
ZL = complex(2, 0.7) 
Zp = complex(20, 100) 
V1 = 7967 #V
ZL1 = ZL*a**2 
Is1 = V1/(Zp + ZL1)
Vs1 = Is1*ZL1
V1s = Vs1/a
RTa = (V1 - abs(Vs1))/abs(Vs1)
print(f'a) RT = {RTa*100}%')

ZL2 = complex(0, -3)*(a**2)
Is2 = V1/(Zp + ZL2)
Vs2 = Is2*ZL2
V2s = Vs2/a
RTb = (V1 - abs(Vs2))/abs(Vs2)
print(f'b) RT = {RTb*100}%')

"""Questão 12 """

from math import acos, cos, sin

a = 230/13800
s = 5000000
FP = 0.8

# Ensaio a curto-circuito
pot1 = 38.1
v1 = 17.1
I1 = 8.7

# Ensaio a vazio
pot2 = 90800 
v2 = 13800
I2 = 21.1

Z1 = v2**2/s 
Req = Z1*0.01
Xeq = Z1*0.05

print(f'a)\nZ1 = {Z1} ohms')
print(f'''Req = {Req} ohms
Xeq = {Xeq} ohms
''') 

Yex2 = I2/v2
angulo2 = acos(pot2/(v2*I2))
Yex2 = complex(Yex2*cos(angulo2), -Yex2*sin(angulo2))
Rc2 = 1/Yex2.real 
X2 = 1/-Yex2.imag

print(f'Yex2 = {Yex2} ohms')
print(f'''RC = {Rc2} ohms
XM = {X2} ohms\n''') 

Is = 4000000/(v2*FP)
Is = complex(Is, -acos(0.8))
VA = v2 + Is*complex(0.38, 1.9)
RT = (abs(VA) - v2)/v2
print(f'b) RT = {RT*100}%\n')

"""Questão 13 """

Rp = 4 
Xp = 8
Rs = 1 
Xs = 2 
Rc = 20
a = 4

Req = Rp + Rs*(a**2)
print(f'a) Req = {Req} ohms')

Xeq = Xp + Xs*(a**2)
print(f'b) Xeq = {Xeq} ohms')

Reqp = Rc*(a**2)
print(f'c) Referenciado ao primário --> Reqp = {Reqp} ohms')

Vg = 50
Ip = Vg/complex(Req + Reqp, Xeq)
print(f'd) Corrente no primário para Vg = 50 V --> Ip = {Ip} A')

Vc = a*Ip*Rc
print(f'e) Tensão para um Vg = 50 V --> Vc = {Vc} V')

"""Questão 14 """

Rp = 4 
Xp = 8 
Rs = 1 
Xs = 2 
Rc = 20
a = 4

Req = Rp + (Rs + Rc)*(a**2)
Xeq = Xp + Xs*(a**2)
Zp = complex(Req, Xeq)
print(f'a) Impedância total é Zp = {Zp}')

Vg = 120 
Ip = Vg/Zp
print(f'b) A corrente no primário para Vg = 120 V é Ip = {Ip} A.')

VeqR= Ip * Req
VeqX = Ip * complex(0, Xeq)
Vc = Ip*complex(0,20*(a**2))

print(f'''c) As tensões em Req, Xeq e Rc refletido são, respectivamente,
  {VeqR} V,
  {VeqX} V
e {Vc} V''')